/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista2;

/**
 *
 * @author Toshiba
 */
public class frmAcuario1 extends javax.swing.JFrame {

    /**
     * Creates new form frmAcuario1
     */
    public frmAcuario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnColeccion = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnColaboradores = new javax.swing.JButton();
        btnNosotros = new javax.swing.JButton();
        btnRetornoAcua = new javax.swing.JButton();
        mapaAcua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnColeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Coleccion.JPG"))); // NOI18N
        getContentPane().add(btnColeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 100));

        btnActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/actividades.JPG"))); // NOI18N
        getContentPane().add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, 140));

        btnColaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/colaboradores.JPG"))); // NOI18N
        getContentPane().add(btnColaboradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 140));

        btnNosotros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nostros.JPG"))); // NOI18N
        getContentPane().add(btnNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 120));

        btnRetornoAcua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/retornoA.JPG"))); // NOI18N
        getContentPane().add(btnRetornoAcua, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 110, 40, 40));

        mapaAcua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/mapaA.JPG"))); // NOI18N
        getContentPane().add(mapaAcua, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 120, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondAcuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAcuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAcuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAcuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAcuario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAcuario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActividades;
    public javax.swing.JButton btnColaboradores;
    public javax.swing.JButton btnColeccion;
    public javax.swing.JButton btnNosotros;
    public javax.swing.JButton btnRetornoAcua;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton mapaAcua;
    // End of variables declaration//GEN-END:variables
}
