/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmAnimal1 extends javax.swing.JFrame {

    /**
     * Creates new form frmAnimal1
     */
    public frmAnimal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetornoA = new javax.swing.JButton();
        btnNextA = new javax.swing.JButton();
        lblAnimal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetornoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/RegresoA1.JPG"))); // NOI18N
        getContentPane().add(btnRetornoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 270, 32, 40));

        btnNextA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nextA.JPG"))); // NOI18N
        btnNextA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextAActionPerformed(evt);
            }
        });
        getContentPane().add(btnNextA, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 273, 28, 30));

        lblAnimal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fonAnimal1.png"))); // NOI18N
        getContentPane().add(lblAnimal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 505));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnimal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnimal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnimal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnimal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnimal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNextA;
    public javax.swing.JButton btnRetornoA;
    private javax.swing.JLabel lblAnimal1;
    // End of variables declaration//GEN-END:variables
}
