/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmAnimal3 extends javax.swing.JFrame {

    /**
     * Creates new form frmAnimal3
     */
    public frmAnimal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnafterA3 = new javax.swing.JButton();
        btnNexta3 = new javax.swing.JButton();
        lblAnima3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnafterA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/afterAnima3.JPG"))); // NOI18N
        getContentPane().add(btnafterA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 37, 33));

        btnNexta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nextAnima3.JPG"))); // NOI18N
        getContentPane().add(btnNexta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, 40));

        lblAnima3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondoAnima3.png"))); // NOI18N
        getContentPane().add(lblAnima3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 516));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAnimal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAnimal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAnimal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAnimal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAnimal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNexta3;
    public javax.swing.JButton btnafterA3;
    private javax.swing.JLabel lblAnima3;
    // End of variables declaration//GEN-END:variables
}
