/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmMapa1 extends javax.swing.JFrame {

    /**
     * Creates new form frmMapa1
     */
    public frmMapa1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCamere = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnTarifa = new javax.swing.JButton();
        btnSalirRapido = new javax.swing.JButton();
        btnSali = new javax.swing.JButton();
        btnOp = new javax.swing.JButton();
        lblmap1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCamere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/camera.JPG"))); // NOI18N
        btnCamere.setPreferredSize(new java.awt.Dimension(73, 41));
        getContentPane().add(btnCamere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 418, 38, 37));

        btnRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Regreso.JPG"))); // NOI18N
        getContentPane().add(btnRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 426, 30, 30));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/next.JPG"))); // NOI18N
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 120, 30, 38));

        btnTarifa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/location.JPG"))); // NOI18N
        getContentPane().add(btnTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 368, 22, 25));

        btnSalirRapido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciofond/salir rapido.JPG"))); // NOI18N
        getContentPane().add(btnSalirRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 30, 30));

        btnSali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciofond/salir.JPG"))); // NOI18N
        getContentPane().add(btnSali, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 30, 30));

        btnOp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciofond/principal.JPG"))); // NOI18N
        getContentPane().add(btnOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 30, 30));

        lblmap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondMap.png"))); // NOI18N
        getContentPane().add(lblmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 507));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMapa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMapa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCamere;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnOp;
    public javax.swing.JButton btnRegreso;
    public javax.swing.JButton btnSali;
    public javax.swing.JButton btnSalirRapido;
    public javax.swing.JButton btnTarifa;
    private javax.swing.JLabel lblmap1;
    // End of variables declaration//GEN-END:variables
}
