/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista2;

/**
 *
 * @author Toshiba
 */
public class frmCamara extends javax.swing.JFrame {

    /**
     * Creates new form frmCamara
     */
    public frmCamara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCapturaCam = new javax.swing.JButton();
        btnRetornoCam = new javax.swing.JButton();
        btnMapaCam = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCapturaCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/CapturaCam.JPG"))); // NOI18N
        getContentPane().add(btnCapturaCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 442, 60, 50));

        btnRetornoCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/RetornoCam.JPG"))); // NOI18N
        getContentPane().add(btnRetornoCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 450, 40, 40));

        btnMapaCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/mapaCam.JPG"))); // NOI18N
        getContentPane().add(btnMapaCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 450, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondCamara_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCamara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCamara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCapturaCam;
    public javax.swing.JButton btnMapaCam;
    public javax.swing.JButton btnRetornoCam;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
