/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista2;

/**
 *
 * @author Toshiba
 */
public class frmRestaurant1 extends javax.swing.JFrame {

    /**
     * Creates new form frmRestaurant1
     */
    public frmRestaurant1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetornoR = new javax.swing.JButton();
        btnMapaR = new javax.swing.JButton();
        btnNextR = new javax.swing.JButton();
        lblRestaurant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetornoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/retornoR.png"))); // NOI18N
        getContentPane().add(btnRetornoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 436, 30, 30));

        btnMapaR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/mapaR.png"))); // NOI18N
        btnMapaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaRActionPerformed(evt);
            }
        });
        getContentPane().add(btnMapaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 434, 39, 30));

        btnNextR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/nextR.png"))); // NOI18N
        btnNextR.setBorder(null);
        getContentPane().add(btnNextR, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 180, 30, 30));

        lblRestaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondRestaurant.png"))); // NOI18N
        getContentPane().add(lblRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMapaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMapaRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRestaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRestaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRestaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRestaurant1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRestaurant1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMapaR;
    public javax.swing.JButton btnNextR;
    public javax.swing.JButton btnRetornoR;
    private javax.swing.JLabel lblRestaurant;
    // End of variables declaration//GEN-END:variables
}
