/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmEleccion extends javax.swing.JFrame {

    /**
     * Creates new form frmEleccion
     */
    public frmEleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHuachipa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsalirRAPIDO = new javax.swing.JButton();
        btnOpcion = new javax.swing.JButton();
        lblFond = new javax.swing.JLabel();
        btnsalir1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHuachipa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoEleecion/tigre.png"))); // NOI18N
        btnHuachipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuachipaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuachipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 120));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        jLabel1.setText("Zoologico de ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 20));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoEleecion/salir rapido.JPG"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 30, 20));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        jLabel2.setText("Huachupa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 20));

        btnsalirRAPIDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoEleecion/salir.JPG"))); // NOI18N
        getContentPane().add(btnsalirRAPIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 30, 20));

        btnOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciofond/principal.JPG"))); // NOI18N
        getContentPane().add(btnOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 30, 20));

        lblFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoEleecion/fonfoEleccion.png"))); // NOI18N
        getContentPane().add(lblFond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 495));

        btnsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoEleecion/salir rapido.JPG"))); // NOI18N
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 30, 20));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        jLabel3.setText("Zoologico de ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuachipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuachipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuachipaActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnHuachipa;
    private javax.swing.JButton btnOpcion;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsalir1;
    private javax.swing.JButton btnsalirRAPIDO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFond;
    // End of variables declaration//GEN-END:variables
}
