/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmMapa3 extends javax.swing.JFrame {

    /**
     * Creates new form frmMapa3
     */
    public frmMapa3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnregresom3 = new javax.swing.JButton();
        btnafterm3 = new javax.swing.JButton();
        btncamara3 = new javax.swing.JButton();
        btnJuegos = new javax.swing.JButton();
        btnAcuarioM = new javax.swing.JButton();
        lblMap3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnregresom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Regresom3.JPG"))); // NOI18N
        getContentPane().add(btnregresom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 430, 40, 40));

        btnafterm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/aftermap3.JPG"))); // NOI18N
        getContentPane().add(btnafterm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 40, 30));

        btncamara3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/camaramap3.JPG"))); // NOI18N
        getContentPane().add(btncamara3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 30, 30));

        btnJuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/juegosmap3.JPG"))); // NOI18N
        getContentPane().add(btnJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 60, 30));

        btnAcuarioM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/btnAcuarioM.JPG"))); // NOI18N
        getContentPane().add(btnAcuarioM, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 67, 60, 50));

        lblMap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondoMapa3.png"))); // NOI18N
        getContentPane().add(lblMap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 514));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcuarioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcuarioMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMapa3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMapa3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcuarioM;
    public javax.swing.JButton btnJuegos;
    public javax.swing.JButton btnafterm3;
    public javax.swing.JButton btncamara3;
    public javax.swing.JButton btnregresom3;
    private javax.swing.JLabel lblMap3;
    // End of variables declaration//GEN-END:variables
}
