/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Toshiba
 */
public class frmTarifa2 extends javax.swing.JFrame {

    /**
     * Creates new form frmTarifa
     */
    public frmTarifa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTarifario = new javax.swing.JButton();
        btn_0_0 = new javax.swing.JButton();
        btn_0_1 = new javax.swing.JButton();
        btn_1_0 = new javax.swing.JButton();
        btn_1_1 = new javax.swing.JButton();
        btn_2_0 = new javax.swing.JButton();
        btn_2_1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRetornoT = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDinero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTarifa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTarifario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/btnTarifario.JPG"))); // NOI18N
        getContentPane().add(btnTarifario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 60));

        btn_0_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[0][0].JPG"))); // NOI18N
        getContentPane().add(btn_0_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, 20));

        btn_0_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[0][1].JPG"))); // NOI18N
        getContentPane().add(btn_0_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 206, 50, 20));

        btn_1_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[1][0].JPG"))); // NOI18N
        getContentPane().add(btn_1_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 233, 60, 18));

        btn_1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[1][1].JPG"))); // NOI18N
        getContentPane().add(btn_1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 232, 50, 17));

        btn_2_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[2][0].JPG"))); // NOI18N
        getContentPane().add(btn_2_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 258, 60, 20));

        btn_2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/[2][1].JPG"))); // NOI18N
        getContentPane().add(btn_2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 257, 50, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetornoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/Regreso.png"))); // NOI18N
        btnRetornoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornoTActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetornoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lblResultado.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 20));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setText("Saldo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblGasto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        lblGasto.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 20));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setText("Gasto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel3.setText("Dinero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        lblDinero.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        lblDinero.setForeground(new java.awt.Color(0, 51, 255));
        lblDinero.setText("580");
        jPanel1.add(lblDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 4, 40, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/bcp.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, 150));

        lblTarifa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fontarifa.png"))); // NOI18N
        getContentPane().add(lblTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 503));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetornoTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTarifa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTarifa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTarifa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTarifa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTarifa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRetornoT;
    public javax.swing.JButton btnTarifario;
    public javax.swing.JButton btn_0_0;
    public javax.swing.JButton btn_0_1;
    public javax.swing.JButton btn_1_0;
    public javax.swing.JButton btn_1_1;
    public javax.swing.JButton btn_2_0;
    public javax.swing.JButton btn_2_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblDinero;
    public javax.swing.JLabel lblGasto;
    public javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTarifa;
    // End of variables declaration//GEN-END:variables
}
